#!/usr/bin/env bash
#
# A local iOS build that cleans up after itself, because this machine runs out
# of disk otherwise — `eas build --local` needs ~10 GB free and the two things
# that eat it are both regenerable:
#
#   • ios/build/Build & friends — Detox's derived data, ~9 GB after an e2e run
#   • build-*.ipa               — ~20 MB each, one per build, kept forever
#
#   scripts/build-ios.sh            prune, build, prune again
#   scripts/build-ios.sh --submit   …and submit the result to TestFlight
#   scripts/build-ios.sh --clean    prune only, build nothing
#   scripts/build-ios.sh --dry-run  say what would be freed, touch nothing
#
# Exit codes: 0 done · 1 something failed · 3 the submission was scheduled but
# its outcome is unconfirmed (see the submit block at the bottom).
#
# NOTE the next Detox build has to run `pod install` after this has pruned
# ios/build. Keeping ios/build/generated does NOT avoid that — tried, and the
# build still failed with "Build input file cannot be found" for files that
# were sitting right there: the codegen output survives, whatever ties it to
# the Pods project does not. scripts/e2e-build.sh (npm run e2e:build) runs
# pod install itself for that reason, so this can prune freely.
set -euo pipefail

cd "$(dirname "$0")/.."

NEEDED_GB="${GOTE_BUILD_MIN_GB:-12}"   # overridable, mostly so the refusal path is testable
DRY=0
CLEAN_ONLY=0
SUBMIT=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --clean) CLEAN_ONLY=1 ;;
    --submit) SUBMIT=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

free_gb() { df -g . | awk 'NR==2 {print $4}'; }
size_of() { [ -e "$1" ] && du -sh "$1" 2>/dev/null | cut -f1 || true; }

drop() { # drop <path> <why>
  local path="$1" why="$2" size
  [ -e "$path" ] || return 0
  size="$(size_of "$path")"
  if [ "$DRY" = 1 ]; then
    echo "  would free ${size:-?}	$path	($why)"
  else
    rm -rf "$path"
    echo "  freed ${size:-?}	$path"
  fi
}

echo "Free space before: $(free_gb) GB"

# 1. Detox's derived data. All of it, including the codegen output: keeping
#    that back bought nothing (see the NOTE above) and left ~40 MB behind.
drop ios/build "regenerated by npm run e2e:build, which runs pod install first"
drop build-device "old device-build derived data"

# 2. Every local .ipa except the newest — those are already on TestFlight, and
#    the newest is kept so there is something to re-submit if a build fails.
newest="$(ls -t build-*.ipa 2>/dev/null | head -1 || true)"
while IFS= read -r ipa; do
  [ -n "$ipa" ] || continue
  [ "$ipa" = "$newest" ] && continue
  drop "$ipa" "already uploaded"
done < <(ls -t build-*.ipa 2>/dev/null || true)

# 3. Old e2e artifact trees and build logs, which accumulate per run.
drop artifacts "detox run artifacts"
drop build-shots "screenshot-run derived data"

echo "Free space after:  $(free_gb) GB"
[ "$DRY" = 1 ] && exit 0
[ "$CLEAN_ONLY" = 1 ] && exit 0

have="$(free_gb)"
if [ "$have" -lt "$NEEDED_GB" ]; then
  echo
  echo "Only ${have} GB free and a local build wants ~${NEEDED_GB} GB." >&2
  echo "Nothing left that this script considers disposable. Look at:" >&2
  echo "  du -sh ~/Library/Developer/CoreSimulator/Devices   (xcrun simctl delete unavailable)" >&2
  echo "  du -sh ~/.npm ~/Library/Caches" >&2
  exit 1
fi

echo
echo "Building (eas build --local, production profile)…"
npx -y eas-cli@latest build -p ios --profile production --local --non-interactive

built="$(ls -t build-*.ipa 2>/dev/null | head -1 || true)"
if [ -z "$built" ] || [ "$built" = "$newest" ]; then
  echo "No new .ipa appeared — the build did not produce one." >&2
  exit 1
fi
echo
echo "Built $built"

# 4. The build is the new newest, so the one it replaced can go.
if [ -n "$newest" ] && [ -e "$newest" ]; then
  drop "$newest" "superseded by $built"
fi
echo "Free space now:    $(free_gb) GB"

# Did a submission run get far enough that EAS owns it now? eas-cli prints
# "Scheduled iOS submission" once the archive is uploaded and queued; anything
# after that — including the status polling this script watches — is the client
# watching work that is already happening on EAS's servers.
scheduled_in() { grep -q "Scheduled iOS submission" "$1"; }
submission_url_in() { grep -o "https://expo.dev/[^ ]*submissions/[^ ]*" "$1" | tail -1; }

if [ "$SUBMIT" = 1 ]; then
  echo
  echo "Submitting $built to App Store Connect…"
  log="$(mktemp -t gote-submit)"
  set +e
  npx -y eas-cli@latest submit -p ios --profile production \
    --path "$built" --non-interactive 2>&1 | tee "$log"
  status="${PIPESTATUS[0]}"
  set -e

  if [ "$status" -eq 0 ]; then
    rm -f "$log"
    exit 0
  fi

  # A dropped connection AFTER the upload is not a failed submission, and
  # reporting it as one sends you re-submitting a build Apple may already have.
  # This happened on build 61: "read ECONNRESET" while polling, long after the
  # archive had gone up.
  if scheduled_in "$log"; then
    echo
    echo "The archive uploaded and the submission was SCHEDULED; only eas-cli's"
    echo "status polling failed, so whether Apple accepted it is unconfirmed."
    echo "Check before re-submitting — a second upload of the same build number"
    echo "is rejected:"
    echo "  $(submission_url_in "$log")"
    echo "  https://appstoreconnect.apple.com/apps/6792750976/testflight/ios"
    echo "$built is kept for a re-submit if it did not land:"
    echo "  npx eas-cli submit -p ios --profile production --path $built"
    rm -f "$log"
    exit 3
  fi

  echo
  echo "Submission failed before it was scheduled — nothing reached EAS." >&2
  echo "$built is kept; re-run with --submit once the cause is fixed." >&2
  rm -f "$log"
  exit 1
fi
