#!/usr/bin/env bash
#
# A local iOS build that cleans up after itself, because this machine runs out
# of disk otherwise — `eas build --local` needs ~10 GB free and the two things
# that eat it are both regenerable:
#
#   • ios/build/Build & friends — Detox's derived data, ~9 GB after an e2e run
#   • build-*.ipa               — ~20 MB each, one per build, kept forever
#
#   scripts/build-ios.sh            prune, build, prune again
#   scripts/build-ios.sh --submit   …and submit the result to TestFlight
#   scripts/build-ios.sh --clean    prune only, build nothing
#   scripts/build-ios.sh --dry-run  say what would be freed, touch nothing
#
# NOTE ios/build/generated is deliberately KEPT. It holds React Native's
# codegen output, written by `pod install` rather than by the build, and
# deleting the whole of ios/build means the next native build fails with a
# wall of "Build input file cannot be found" until pod install is run again.
set -euo pipefail

cd "$(dirname "$0")/.."

NEEDED_GB="${GOTE_BUILD_MIN_GB:-12}"   # overridable, mostly so the refusal path is testable
DRY=0
CLEAN_ONLY=0
SUBMIT=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --clean) CLEAN_ONLY=1 ;;
    --submit) SUBMIT=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

free_gb() { df -g . | awk 'NR==2 {print $4}'; }
size_of() { [ -e "$1" ] && du -sh "$1" 2>/dev/null | cut -f1 || true; }

drop() { # drop <path> <why>
  local path="$1" why="$2" size
  [ -e "$path" ] || return 0
  size="$(size_of "$path")"
  if [ "$DRY" = 1 ]; then
    echo "  would free ${size:-?}	$path	($why)"
  else
    rm -rf "$path"
    echo "  freed ${size:-?}	$path"
  fi
}

echo "Free space before: $(free_gb) GB"

# 1. Detox's derived data — everything except the codegen output.
for sub in Build ModuleCache.noindex SDKExplicitPrecompiledModules \
           SDKStatCaches.noindex CompilationCache.noindex Logs; do
  drop "ios/build/$sub" "regenerated by the next e2e build"
done
drop build-device "old device-build derived data"

# 2. Every local .ipa except the newest — those are already on TestFlight, and
#    the newest is kept so there is something to re-submit if a build fails.
newest="$(ls -t build-*.ipa 2>/dev/null | head -1 || true)"
while IFS= read -r ipa; do
  [ -n "$ipa" ] || continue
  [ "$ipa" = "$newest" ] && continue
  drop "$ipa" "already uploaded"
done < <(ls -t build-*.ipa 2>/dev/null || true)

# 3. Old e2e artifact trees and build logs, which accumulate per run.
drop artifacts "detox run artifacts"
drop build-shots "screenshot-run derived data"

echo "Free space after:  $(free_gb) GB"
[ "$DRY" = 1 ] && exit 0
[ "$CLEAN_ONLY" = 1 ] && exit 0

have="$(free_gb)"
if [ "$have" -lt "$NEEDED_GB" ]; then
  echo
  echo "Only ${have} GB free and a local build wants ~${NEEDED_GB} GB." >&2
  echo "Nothing left that this script considers disposable. Look at:" >&2
  echo "  du -sh ~/Library/Developer/CoreSimulator/Devices   (xcrun simctl delete unavailable)" >&2
  echo "  du -sh ~/.npm ~/Library/Caches" >&2
  exit 1
fi

echo
echo "Building (eas build --local, production profile)…"
npx -y eas-cli@latest build -p ios --profile production --local --non-interactive

built="$(ls -t build-*.ipa 2>/dev/null | head -1 || true)"
if [ -z "$built" ] || [ "$built" = "$newest" ]; then
  echo "No new .ipa appeared — the build did not produce one." >&2
  exit 1
fi
echo
echo "Built $built"

# 4. The build is the new newest, so the one it replaced can go.
if [ -n "$newest" ] && [ -e "$newest" ]; then
  drop "$newest" "superseded by $built"
fi
echo "Free space now:    $(free_gb) GB"

if [ "$SUBMIT" = 1 ]; then
  echo
  echo "Submitting $built to App Store Connect…"
  npx -y eas-cli@latest submit -p ios --profile production --path "$built" --non-interactive
fi
